apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus
    monitoring-key: "{{ grafana_label_value }}"
  name: scm-services
spec:
  endpoints:
    - interval: 5s
      port: http
      path: /metrics
  namespaceSelector:
    matchNames:
      - '{{ namespace }}'
  selector:
    matchLabels:
      monitoring: {{ prometheus_ServiceMonitor_label }}
