apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  finalizers:
    - subscriptions.messaging.knative.dev
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: scm-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: scm-echo