---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scm-kafka-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scm-kafka-echo
  template:
    metadata:
      labels:
        app: scm-kafka-echo
        app.kubernetes.io/component: scm-kafka-echo
        app.kubernetes.io/instance: scm-kafka-echo
        app.kubernetes.io/name: scm-kafka-echo
        app.openshift.io/runtime: quarkus
    spec:
      containers:
        - env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: scm-cluster-kafka-bootstrap.SCM_NAMESPACE.svc:9092
          name: scm-kafka-echo
          image: quay.io/gbengataylor/scm-kafka-echo
          imagePullPolicy: IfNotPresent