# pre-req knative-kafka installed in cluster
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: scm-cluster-kafka-source
  namespace: test
  labels:
    app: scm-cluster-kafka-source
    app.kubernetes.io/instance: scm-cluster-kafka-source
    app.kubernetes.io/component: scm-cluster-kafka-source
    app.kubernetes.io/name: scm-cluster-kafka-source
    app.kubernetes.io/part-of: event-sources-app
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
spec:
  # this requires that the namespace be included otherwise the broker will not be found and the kafka source will not be ready
  bootstrapServers: [scm-cluster-kafka-brokers.namespace.svc:9092]
  topics: [scm-file-topic]
  consumerGroup: scm-file-db-mapper
  net:
    sasl:
      user: {}
      password: {}
    tls:
      caCert: {}
      cert: {}
      key: {}
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1
      kind: Channel
      name: channel