psql_app_name: "{{ scm_backend_psql_name }}"
application_name: scm-backend

postgresql_pv_capacity: 5Gi
postgresql_version: 12-el8
postgresql_is_namespace: openshift
postgresql_service_account: "{{ psql_app_name }}"
psql_user_name: "{{ scm_psql_user_name }}"
psql_user_passwd: "{{ scm_psql_passwd }}"
psql_db_name: "{{ scm_psql_db_name }}"
psql_credentials_secret: "{{ psql_app_name }}"
postgresql_max_prepared_transactions: 100
postgresql_max_connections: 100
postgresql_init_configmap: "{{ psql_app_name }}-init"
postgresql_memory_limit: 512Mi
postgresql_cpu_limit: 500m
postgresql_memory_request: 256Mi
postgresql_cpu_request: 100m
undeploy_psql_bpm: "false"

service_account: "{{ application_name }}"
application_properties: application.properties
application_configmap: "{{ application_name }}"
application_configmap_key: "{{ application_properties }}"
binary_imagestream_template: binary-imagestream.yml 
service_image: quay.io/redhat_naps_da/himss_2022_scm-backend-jvm
service_image_tag: 0.0.3
application_template: scm-backend-service.yml
