---

#- name: delete deployment config
- name: delete knative service
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    #kind: dc
    kind: ksvc

# - name: delete service
#   oc_obj:
#     oc_binary: "{{ openshift_cli }}"
#     state: absent
#     name: "{{ application_name }}"
#     namespace: "{{ namespace }}"
#     kind: service

- name: delete imagestream in the {{ namespace }} project
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    kind: imagestream

- name: "delete configmap {{ application_configmap }}"
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ application_configmap }}"
    namespace: "{{ namespace }}"
    kind: configmap
