apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: {{ grafana_datasource_name }}
spec:
  name: middleware.yaml
  datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://{{ prometheus_service_name }}:9090
      isDefault: false
      version: 1
      editable: true
      jsonData:
        timeInterval: "5s"
    - name: PostgreSQL
      type: postgres
      url: {{ scm_backend_psql_name }}.{{ project_name }}:5432
      database: {{ scm_psql_db_name }}
      user: {{ scm_psql_user_name }}
      secureJsonData:
        password: {{ scm_psql_passwd }}
      jsonData:
        sslmode: "disable"
      editable: true
      access: "proxy"
      isDefault: true
