---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: '{{ prometheus_cr_name }}'
  name: '{{ prometheus_cr_name }}'
spec:

  # https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/getting-started.md#expose-the-prometheus-admin-api
  enableAdminAPI: true

  # Prometheus Scrape Configs
  # https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/additional-scrape-config.md
  additionalScrapeConfigs:
    key: prometheus-additional.yaml
    name: additional-scrape-configs

  replicas: 1
  containers:
  - args:
    - -provider=openshift
    - -https-address=:9091
    - -http-address=
    - -email-domain=*
    - -upstream=http://localhost:9090
    - -openshift-service-account={{ prometheus_serviceaccount_name }}
    - '-openshift-sar={"resource": "namespaces", "verb": "get"}'
    - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb":"get"}}'
    - -tls-cert=/etc/tls/private/tls.crt
    - -tls-key=/etc/tls/private/tls.key
    - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
    - -cookie-secret-file=/etc/proxy/secrets/session_secret
    - -openshift-ca=/etc/pki/tls/cert.pem
    - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    - -skip-auth-regex=^/metrics
    image: '{{ prometheus_auth_proxy_image }}'
    name: prometheus-proxy
    ports:
    - containerPort: 9091
      name: oproxy
    resources: {}
    volumeMounts:
    - mountPath: /etc/tls/private
      name: 'secret-{{ prometheus_tls_secret }}'
    - mountPath: /etc/proxy/secrets
      name: 'secret-{{ prometheus_oauth_proxy_secret }}'
  externalUrl: 'https://{{ prometheus_route_name }}-{{ namespace }}.{{ ocp_domain }}'
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  resources:
    requests:
      cpu: '{{ prometheus_requests_cpu }}'
      memory: '{{ prometheus_requests_memory }}'
    limits:
      cpu: '{{ prometheus_limits_cpu }}'
      memory: '{{ prometheus_limits_memory }}' 
  retention: '{{ prometheus_retention }}'
  ruleNamespaceSelector: {}
  ruleSelector: {}
  secrets:
  - '{{ prometheus_tls_secret }}'
  - '{{ prometheus_oauth_proxy_secret }}'
  serviceAccountName: {{ prometheus_serviceaccount_name }}
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: '{{ prometheus_storage_request }}'
