---

- set_fact:
    namespace: "{{ keda_namepsace }}"
    resources_dir: "{{ resources_base_dir }}/keda"
    work_dir_name: keda
- include_role:
    name: ../roles/keda
  when: >
    ACTION is not defined or
    ACTION is none or
    ACTION|trim() == "" or
    ACTION|trim() == "install"
- include_role:
    name: ../roles/keda
    tasks_from: uninstall
  when: >
    ACTION is defined and
    ACTION|trim() == "uninstall"
